version: "3"
services:
  terraria:
    container_name: terraria
    image: ryshe/terraria:vanilla-latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - WORLD_FILENAME=Stardew.wld
      # - CONFIGPATH=config.json
    ports:
      - 7777:7777
    volumes:
      - "./world:/root/.local/share/Terraria/Worlds"
      - "./config:/config"
    restart: unless-stopped