version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    env_file: ".env"
    environment:
      SERVER_NAME: "Unstarry Night"
      EULA: "TRUE"
      TYPE: "PAPER"
      MAX_MEMORY: "3G"
      VERSION: "1.19"
      LEVEL: "unstarry_night"
      SPIGET_RESOURCES: "8631" # Core Protect
      ENFORCE_WHITELIST: "TRUE"
    restart: always    

  mysql:
    image: mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    env_file: ".env"